# Generated by Django 4.1.2 on 2022-10-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_activity_activitie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitie',
            old_name='user',
            new_name='email',
        ),
    ]
