# Generated by Django 4.1.2 on 2022-10-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_activitie_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='was_logedout',
            field=models.BooleanField(default=False),
        ),
    ]
