# Generated by Django 4.1.2 on 2022-10-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='example',
        ),
    ]
